config/routes.rb
Emailer::Application.routes.draw do

  root to: 'contact#home'

  match '/help', to: 'contact#help'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/message.rb
class Message

	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor :name, :email, :subject, :body

	validates :name, :email, :subject, :body, presence:true
	validates :email, format: { with: %r{.+@.+\..+} }, :allow_blank => true


	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def persisted?
		false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
		@message = Message.new
	end

	def home
	end

	def help
	end

	def create
		@message = Message.new(params[:message])

		if @message.valid?
			NotificationsMailer.new_message(@message).deliver
			redirect_to(home_path, notice: "Message was successfully sent.")
		else
			flash.now.alert = "Please fill all fields."
			render :new
		end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#returns full title on a per page basis
	def full_title(page_title)
		base_title = "Phalon Application"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/help.html.erb
<% provide(:title, 'Help') %>
<div class="center hero-unit">
<h2>You are not allowed to use this Application if you are not Phalon Lemupah! Sorry.</h2>
</div>

app/views/contact/home.html.erb
<% provide(:title, 'Home')%>
<div class="center hero-unit">
<h1>Welcome to the Phalon App</h1>
<h2>
Please sign in by clicking the button below.
</h2>
<%= link_to "Sign in now!", '#', class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/contact/new.html.erb
<% provide(:title, 'Email') %>
<%= form_for @message, url: contact_path do |f| %>

	<fieldset class="fields">
	    <div class="field">
	      <%= f.label :name %>
	      <%= f.text_field :name %>
	    </div>
	    
	    <div class="field">
	      <%= f.label :email %>
	      <%= f.text_field :email %>
	    </div>
	    <div class="field">
	      <%= f.label :subject %>
	      <%= f.text_field :subject %>
	    </div>
	    
	    <div class="field">
	      <%= f.label :body %>
	      <%= f.text_area :body %>
	    </div>
  	</fieldset>
  
  	<fieldset class="actions">
    	<%= f.submit "Send" %>
  	</fieldset>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "phalon app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Sign in", '#' %></li>
              <li><%= link_to "Send email",    contact_path %></li>
              <li><%= link_to "Help",    help_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>